### PR TITLE
implement function getTermEnd

### PR DESCRIPTION
**Pull request by DasilvaB**
Wanted to make sure I'm on the right path and sort out any issues now before pushing more functions since most are very similar. 

Edit** Okay, I think I finally got it, still learning GitHub, so sorry for all the changes that might happen!

Edit** So the function that was implemented here was getTermEnd not getTermID, commit 1 says it was getTermID.

### CODE REVIEW

**Comment by afig** [comment]
Thanks for getting this started @DasilvaB. The PR seems to be structured well (merging into the correct branch, etc.).

The function works as expected, however, the implementation could actually be a lot simpler. Selecting an attribute in a query that matches 0 rows already returns `NULL`, so the entire function could be implemented as:

```sql
CREATE OR REPLACE FUNCTION getTermEnd(termID INT)
RETURNS DATE
AS
$$
   SELECT EndDate 
   FROM Term
   WHERE ID = $1;
$$ LANGUAGE sql
   SECURITY DEFINER
   SET search_path FROM CURRENT
   STABLE
   RETURNS NULL ON NULL INPUT;
```

In general, `RETURN QUERY` is only used when you do not yet want to exit the function. The function will automatically return when the end is reached.

**Review by jrm86 — CHANGES_REQUESTED** [review]
It will be sufficient to have the query alone.  I had a similar misunderstanding with another function elsewhere (whether there's a difference between returning an empty table or returning NULL).  If there are no results to return, the function will return NULL.

**Review by jrm86 — APPROVED** [review]
Looks good; approving

**Review by afig — APPROVED** [review]
Looks good. Thanks @DasilvaB

**Pull request merged**
