### PR TITLE
Added getInstructorName function

### PR DESCRIPTION
**Pull request by jrm86**
Added a helper function to return an instructor's full name.  Works in adhoc tests.

### CODE REVIEW

**Review by afig — COMMENTED** [review]
Thanks for implementing this helper function @jrm86. Overall, the function behavior looks good. I suggest the following changes:

- Remove `alpha.` schema qualification from table names - this allows for easier implementation of multi-tenancy. The correct schema will be set during function definition.
- Add `SECURITY DEFINER` to functions (otherwise users will not be able to get information) - at least for `getInstructorName()`
- Add `SET search_path FROM CURRENT` (this sets the correct schema) - at least for `getInstructorName()`
- L375: `insstructorID` -> `instructorID`

**Comment by jrm86** [comment]
Thank you for the corrections @afig.  Changes have been made.

**Review by DasilvaB — APPROVED** [review]
Changes look great.

**Review by afig — APPROVED** [review]
Changes look good. A few `alpha.` schema qualifications remain in the privilege adjustments for `getInstructor`. However, I am okay with merging this in as-is. We can deal with any remaining schema qualifications during a check before submission.

**Pull request merged**
