### PR TITLE
Added roles to prepareServer script

### PR DESCRIPTION
**Pull request by jrm86**
Pretty straight forward. Added role creation to account for new rolls needed to employ role based access controls.  Addresses Issue #1 .

### CODE REVIEW

**Review by afig — COMMENTED** [review]
Changes so far look good, but a couple of things should likely be addressed before merging this in:

- Currently the PR is merging into `master`, but should probably be merging into `dev`. This was also an issue with the PR merged on Friday, but I missed correcting it then.
- We should probably grant the new roles to the existing `gradebook` role, otherwise functions that run as `gradebook` will not be able to grant these new roles to users. It seems like this could be done on one line.

Sidenote: We may eventually have to look at what L80 is currently doing (`GRANT gradebook TO GB_Webapp`). The comment preceding the statement seems to indicate that it will not be necessary after making function execute in the context of the `gradebook` role, which should be finished during M6.

**Comment by jrm86** [comment]
Thanks for the feedback @afig.  Latest commit grants new roles to the `gradebook` role. PR #7 will bring the dev branch up to date.

**Review by afig — COMMENTED** [review]
New changes look great. Following our discussion in-person, we should also make the following changes:

- Make capitalization of role names consistent
  - L88 `gb_dbadmin` -> `GB_DBAdmin`
  - L100-101 - Capitalize role names to match their capitalization elsewhere in the file
- Add an `alpha_` prefix to all role names (except for the `gradebook` role)
- Remove the grant of `pg_signal_backend` (may want to leave a comment about it previously being there)
- Remove the grant of `CREATEDB` to the `gradebook` role (again, may want to leave a comment noting its removal)
- Change the `gradebook` role to `alpha`

**Review by DasilvaB — COMMENTED** [review]
I think @afig hit the main points, besides that though awesome job!

**Review by afig — APPROVED** [review]
Thanks for all of the great revisions @jrm86. This looks ready to merge.

I predict that there might be an issue in the future with the `GB_Webapp` role, but that can be addressed in another branch.

**Comment by jrm86** [comment]
Thanks @afig and @DasilvaB for the feedback.  Once @DasilvaB approves, we'll be good to go!

**Review by DasilvaB — APPROVED** [review]

**Pull request merged**
