### PR TITLE
Completed Milestone 5

### PR DESCRIPTION
**Pull request by jrm86**
Planned out functions and created stubs.

### CODE REVIEW

**Review by afig — COMMENTED** [review]
Thanks for making this pull request @jrm86. Overall looks pretty good, but we should probably remove the `.gitignore` to avoid issues in the future. If we need to, we can add one later for specific files.

**Comment by jrm86** [comment]
Thanks for the review @afig, entry in .gitignore

**Review by DasilvaB — APPROVED** [review]
Everything looks good to go.

**Comment by jrm86** [comment]
@afig, If you approve, I'll merge so we can create an up-to-date branch for M6.

**Review by afig — APPROVED** [review]
Looks good to merge. Thanks again for the fixes made to the stubs @jrm86

**Pull request merged**
